version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      - CATALOG_SERVER=http://catalog:5001
      - ORDER_SERVER=http://order:5002
    depends_on:
      - catalog-1
      - order

 catalog-1:
    build: ./catalog
    ports:
      - "5001:5001"  
    volumes:
      - ./catalog/catalog_data.json:/app/catalog_data.json
    hostname: catalog-1
    environment:
      - CATALOG_REPLICAS=http://catalog-1:5001,http://catalog-2:5001
      - PORT=5001
      - HOSTNAME=catalog-1
    networks:
      - app-network
      

  order:
    build: ./order
    ports:
      - "5002:5002"
    environment:
      - CATALOG_SERVER=http://catalog:5001
    volumes:
      - ./order/order_log.txt:/app/order_log.txt
